[theme]
primaryColor        = "#E62984"
backgroundColor     = "#FBF7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor           = "#2A1622"
font                = "sans serif"

[server]
maxUploadSize = 5
headless      = true

[browser]
gatherUsageStats = false
